#!/usr/bin/env python3
"""Replace common English phrases with Vietnamese in api-specs/openapi/vi/paths/**/*.yaml.
Run from project root. Safe to run multiple times (idempotent for already-translated text).
"""
import os
from pathlib import Path

REPLACEMENTS = [
    ("description: Instance ID\n", "description: Định danh instance\n"),
    ("description: Instance not found\n", "description: Không tìm thấy instance\n"),
    ("description: Invalid request\n", "description: Yêu cầu không hợp lệ\n"),
    ("description: Internal server error\n", "description: Lỗi máy chủ\n"),
    ("description: Server error\n", "description: Lỗi máy chủ\n"),
    ("description: CORS preflight response\n", "description: Phản hồi CORS preflight\n"),
    ("description: Area ID\n", "description: Định danh vùng (area ID)\n"),
    ("description: The unique identifier of the instance\n", "description: Định danh duy nhất của instance\n"),
    ("description: The unique identifier of the line to retrieve\n", "description: Định danh duy nhất của đường cần lấy\n"),
    ("description: The unique identifier of the line to update\n", "description: Định danh duy nhất của đường cần cập nhật\n"),
    ("description: The unique identifier of the line to delete\n", "description: Định danh duy nhất của đường cần xóa\n"),
    ("description: List of crossing lines\n", "description: Danh sách đường vượt (crossing lines)\n"),
    ("description: All lines deleted successfully\n", "description: Đã xóa tất cả lines thành công\n"),
    ("description: List of font files\n", "description: Danh sách file font\n"),
    ("description: List of video files\n", "description: Danh sách file video\n"),
    ("description: List of instances\n", "description: Danh sách instance\n"),
    ("description: List of supported classes\n", "description: Danh sách class được hỗ trợ\n"),
    ("description: List of face subjects\n", "description: Danh sách face subject\n"),
    ("description: List of face subjects retrieved successfully\n", "description: Đã lấy danh sách face subject thành công\n"),
    ("description: All face subjects deleted successfully\n", "description: Đã xóa tất cả face subject thành công\n"),
    ("description: List of exclusion areas\n", "description: Danh sách vùng loại trừ (exclusion areas)\n"),
    ("description: All exclusion areas deleted successfully\n", "description: Đã xóa tất cả vùng loại trừ thành công\n"),
    ("description: All lines deleted successfully\n", "description: Đã xóa tất cả lines thành công\n"),
    ("description: List of templates retrieved successfully\n", "description: Đã lấy danh sách template thành công\n"),
    ("description: List of solutions\n", "description: Danh sách solution\n"),
    ("description: List of nodes retrieved successfully\n", "description: Đã lấy danh sách node thành công\n"),
    ("description: Delete all instances operation completed\n", "description: Đã hoàn thành thao tác xóa tất cả instance\n"),
    ("description: Failed to restart instance\n", "description: Khởi động lại instance thất bại\n"),
    ("description: Failed to stop instance\n", "description: Dừng instance thất bại\n"),
    ("description: Failed to start instance\n", "description: Khởi động instance thất bại\n"),
    ("description: Successfully configured stream output\n", "description: Đã cấu hình stream output thành công\n"),
    ("description: Invalid request (invalid output type or missing required fields)\n", "description: Yêu cầu không hợp lệ (loại output sai hoặc thiếu trường bắt buộc)\n"),
    ("description: Invalid request (invalid input type or missing required fields)\n", "description: Yêu cầu không hợp lệ (loại input sai hoặc thiếu trường bắt buộc)\n"),
    ("description: Invalid request or validation failed\n", "description: Yêu cầu không hợp lệ hoặc validation thất bại\n"),
    ("description: Invalid request (missing file, invalid image format, etc.)\n", "description: Yêu cầu không hợp lệ (thiếu file, định dạng ảnh không hợp lệ, v.v.)\n"),
    # Với thụt lề (parameter/response trong path)
    ("      description: The unique identifier of the instance\n", "      description: Định danh duy nhất của instance\n"),
    ("      description: The unique identifier of the line to retrieve\n", "      description: Định danh duy nhất của đường cần lấy\n"),
    ("      description: The unique identifier of the line to update\n", "      description: Định danh duy nhất của đường cần cập nhật\n"),
    ("      description: The unique identifier of the line to delete\n", "      description: Định danh duy nhất của đường cần xóa\n"),
    ("        description: List of crossing lines\n", "        description: Danh sách đường vượt (crossing lines)\n"),
    ("        description: Line retrieved successfully\n", "        description: Đã lấy đường thành công\n"),
    ("        description: Instance or line not found\n", "        description: Không tìm thấy instance hoặc đường\n"),
    ("        description: Line updated successfully\n", "        description: Đã cập nhật đường thành công\n"),
    ("        description: Bad request (invalid coordinates or parameters)\n", "        description: Yêu cầu không hợp lệ (tọa độ hoặc tham số sai)\n"),
    ("        description: All lines deleted successfully\n", "        description: Đã xóa tất cả đường thành công\n"),
    # Bổ sung: response/success
    ("description: Unique identifier of the instance (UUID)\n", "description: Định danh duy nhất của instance (UUID)\n"),
    ("description: Instance configuration\n", "description: Cấu hình instance\n"),
    ("description: Config value set successfully\n", "description: Đã thiết lập giá trị cấu hình thành công\n"),
    ("description: Batch start operation completed\n", "description: Đã hoàn thành thao tác khởi động hàng loạt\n"),
    ("description: Batch stop operation completed\n", "description: Đã hoàn thành thao tác dừng hàng loạt\n"),
    ("description: Array of instance IDs to start\n", "description: Mảng định danh instance cần khởi động\n"),
    ("description: Array of instance IDs to stop\n", "description: Mảng định danh instance cần dừng\n"),
    ("description: Node details retrieved successfully\n", "description: Đã lấy chi tiết node thành công\n"),
    ("description: Node updated successfully\n", "description: Đã cập nhật node thành công\n"),
    ("description: Node deleted successfully\n", "description: Đã xóa node thành công\n"),
    ("description: Node not found\n", "description: Không tìm thấy node\n"),
    ("description: Node created successfully\n", "description: Đã tạo node thành công\n"),
    ("description: Instance updated successfully\n", "description: Đã cập nhật instance thành công\n"),
    ("description: Instance deleted successfully\n", "description: Đã xóa instance thành công\n"),
    ("description: Instance started successfully\n", "description: Đã khởi động instance thành công\n"),
    ("description: Instance stopped successfully\n", "description: Đã dừng instance thành công\n"),
    ("description: Instance unloaded successfully\n", "description: Đã gỡ instance khỏi bộ nhớ thành công\n"),
    ("description: Instance not loaded\n", "description: Instance chưa được nạp\n"),
    ("description: Instance details\n", "description: Chi tiết instance\n"),
    ("description: Solution not found\n", "description: Không tìm thấy solution\n"),
    ("description: Solution updated successfully\n", "description: Đã cập nhật solution thành công\n"),
    ("description: Solution deleted successfully\n", "description: Đã xóa solution thành công\n"),
    ("description: Default solution loaded successfully\n", "description: Đã nạp solution mặc định thành công\n"),
    ("description: Default solution not found\n", "description: Không tìm thấy solution mặc định\n"),
    ("description: Template details retrieved successfully\n", "description: Đã lấy chi tiết template thành công\n"),
    ("description: Template not found\n", "description: Không tìm thấy template\n"),
    ("description: Statistics retrieved successfully\n", "description: Đã lấy thống kê thành công\n"),
    ("description: Line deleted successfully\n", "description: Đã xóa đường thành công\n"),
    ("description: Lines updated successfully\n", "description: Đã cập nhật đường thành công\n"),
    ("description: Counting line created successfully\n", "description: Đã tạo đường đếm thành công\n"),
    ("description: Tailgating line created successfully\n", "description: Đã tạo đường bám đuôi thành công\n"),
    ("description: PIP configured successfully\n", "description: Đã cấu hình PIP thành công\n"),
    ("description: PIP configuration\n", "description: Cấu hình PIP\n"),
    ("description: LPR configured successfully\n", "description: Đã cấu hình LPR thành công\n"),
    ("description: LPR configuration\n", "description: Cấu hình LPR\n"),
    ("description: Feature extraction configured successfully\n", "description: Đã cấu hình trích xuất đặc trưng thành công\n"),
    ("description: Feature extraction configuration\n", "description: Cấu hình trích xuất đặc trưng\n"),
    ("description: Face detection configured successfully\n", "description: Đã cấu hình nhận diện khuôn mặt thành công\n"),
    ("description: Performance profile configured successfully\n", "description: Đã cấu hình hồ sơ hiệu năng thành công\n"),
    ("description: Performance profile configuration\n", "description: Cấu hình hồ sơ hiệu năng\n"),
    ("description: Analytics entities retrieved successfully\n", "description: Đã lấy thực thể analytics thành công\n"),
    ("description: Input settings updated successfully\n", "description: Đã cập nhật cài đặt đầu vào thành công\n"),
    ("description: Stream output configuration\n", "description: Cấu hình đầu ra stream\n"),
    ("description: Instance output and processing results\n", "description: Đầu ra instance và kết quả xử lý\n"),
    # Bad request / errors
    ("description: Bad request (invalid input or missing required fields)\n", "description: Yêu cầu không hợp lệ (đầu vào sai hoặc thiếu trường bắt buộc)\n"),
    ("description: Bad request (missing parameters field)\n", "description: Yêu cầu không hợp lệ (thiếu trường parameters)\n"),
    ("description: Bad request (parsing error or invalid arguments)\n", "description: Yêu cầu không hợp lệ (lỗi phân tích hoặc tham số không hợp lệ)\n"),
    ("description: Bad request (validation failed)\n", "description: Yêu cầu không hợp lệ (validation thất bại)\n"),
    ("description: Conflict (node is currently in use)\n", "description: Xung đột (node đang được sử dụng)\n"),
    # Parameter descriptions (4 spaces - path level)
    ("      description: Unique identifier of the instance (UUID)\n", "      description: Định danh duy nhất của instance (UUID)\n"),
    ("      description: Unique node identifier\n", "      description: Định danh node duy nhất\n"),
    ("      description: Unique template identifier\n", "      description: Định danh template duy nhất\n"),
    ("      description: Instance ID (UUID)\n", "      description: Định danh instance (UUID)\n"),
    ("        description: Unique identifier of the instance (UUID)\n", "        description: Định danh duy nhất của instance (UUID)\n"),
    ("        description: Instance configuration\n", "        description: Cấu hình instance\n"),
    ("        description: Config value set successfully\n", "        description: Đã thiết lập giá trị cấu hình thành công\n"),
    ("        description: Bad request (invalid input or missing required fields)\n", "        description: Yêu cầu không hợp lệ (đầu vào sai hoặc thiếu trường bắt buộc)\n"),
    ("        description: Node details retrieved successfully\n", "        description: Đã lấy chi tiết node thành công\n"),
    ("        description: Node not found\n", "        description: Không tìm thấy node\n"),
    ("        description: Node updated successfully\n", "        description: Đã cập nhật node thành công\n"),
    ("        description: Bad request (missing parameters field)\n", "        description: Yêu cầu không hợp lệ (thiếu trường parameters)\n"),
    ("        description: Node deleted successfully\n", "        description: Đã xóa node thành công\n"),
    ("        description: Conflict (node is currently in use)\n", "        description: Xung đột (node đang được sử dụng)\n"),
    ("        description: List of pre-configured nodes\n", "        description: Danh sách node cấu hình sẵn\n"),
    ("        description: List of available pre-configured nodes\n", "        description: Danh sách node cấu hình sẵn có sẵn\n"),
    ("        description: List of default solutions\n", "        description: Danh sách solution mặc định\n"),
    ("        description: Default solution ID to load\n", "        description: Định danh solution mặc định cần nạp\n"),
    ("        description: Default solution loaded successfully\n", "        description: Đã nạp solution mặc định thành công\n"),
    ("        description: Loaded solution ID\n", "        description: Định danh solution đã nạp\n"),
    ("                  description: Loaded solution ID\n", "                  description: Định danh solution đã nạp\n"),
    ("        description: Default solution not found\n", "        description: Không tìm thấy solution mặc định\n"),
    ("        description: Solution not found\n", "        description: Không tìm thấy solution\n"),
    ("        description: Solution updated successfully\n", "        description: Đã cập nhật solution thành công\n"),
    ("        description: Bad request (validation failed)\n", "        description: Yêu cầu không hợp lệ (validation thất bại)\n"),
    ("        description: Solution deleted successfully\n", "        description: Đã xóa solution thành công\n"),
    ("        description: Instance updated successfully\n", "        description: Đã cập nhật instance thành công\n"),
    ("        description: Bad request (parsing error or invalid arguments)\n", "        description: Yêu cầu không hợp lệ (lỗi phân tích hoặc tham số không hợp lệ)\n"),
    ("        description: Instance deleted successfully\n", "        description: Đã xóa instance thành công\n"),
    ("        description: Instance details\n", "        description: Chi tiết instance\n"),
    ("        description: Instance unloaded successfully\n", "        description: Đã gỡ instance khỏi bộ nhớ thành công\n"),
    ("        description: Instance not loaded\n", "        description: Instance chưa được nạp\n"),
    ("        description: Instance started successfully\n", "        description: Đã khởi động instance thành công\n"),
    ("        description: Instance stopped successfully\n", "        description: Đã dừng instance thành công\n"),
    ("        description: Input settings updated successfully\n", "        description: Đã cập nhật cài đặt đầu vào thành công\n"),
    ("        description: Stream output configuration\n", "        description: Cấu hình đầu ra stream\n"),
    ("        description: Bad request (invalid input or missing required fields)\n", "        description: Yêu cầu không hợp lệ (đầu vào sai hoặc thiếu trường bắt buộc)\n"),
    ("        description: Line(s) created successfully. Returns single line object for single request, or object with metadata\n", "        description: Đã tạo đường thành công. Trả về một object đường với yêu cầu đơn, hoặc object kèm metadata với yêu cầu mảng\n"),
    ("        description: Bad request (invalid coordinates or parameters)\n", "        description: Yêu cầu không hợp lệ (tọa độ hoặc tham số sai)\n"),
    ("        description: Counting line created successfully\n", "        description: Đã tạo đường đếm thành công\n"),
    ("        description: Created line ID\n", "                  description: Định danh đường đã tạo\n"),
    ("        description: Tailgating line created successfully\n", "        description: Đã tạo đường bám đuôi thành công\n"),
    ("        description: Line deleted successfully\n", "        description: Đã xóa đường thành công\n"),
    ("        description: Lines updated successfully\n", "        description: Đã cập nhật đường thành công\n"),
    ("        description: Number of lines updated\n", "                  description: Số đường đã cập nhật\n"),
    ("        description: Analytics lines retrieved successfully\n", "        description: Đã lấy đường analytics thành công\n"),
    ("        description: PIP configured successfully\n", "        description: Đã cấu hình PIP thành công\n"),
    ("        description: PIP configuration\n", "        description: Cấu hình PIP\n"),
    ("                description: Enable picture-in-picture\n", "                description: Bật picture-in-picture\n"),
    ("        description: PIP enabled status\n", "                  description: Trạng thái bật PIP\n"),
    ("        description: LPR configured successfully\n", "        description: Đã cấu hình LPR thành công\n"),
    ("        description: LPR configuration\n", "        description: Cấu hình LPR\n"),
    ("                description: Enable license plate recognition\n", "                description: Bật nhận diện biển số\n"),
    ("        description: Feature extraction configured successfully\n", "        description: Đã cấu hình trích xuất đặc trưng thành công\n"),
    ("        description: Feature extraction configuration\n", "        description: Cấu hình trích xuất đặc trưng\n"),
    ("                description: Array of feature extraction types\n", "                description: Mảng loại trích xuất đặc trưng\n"),
    ("                  description: Array of configured feature extraction types\n", "                  description: Mảng loại trích xuất đặc trưng đã cấu hình\n"),
    ("        description: Performance profile configured successfully\n", "        description: Đã cấu hình hồ sơ hiệu năng thành công\n"),
    ("        description: Performance profile configuration\n", "        description: Cấu hình hồ sơ hiệu năng\n"),
    ("                description: Performance profile name\n", "                description: Tên hồ sơ hiệu năng\n"),
    ("        description: Face detection configured successfully\n", "        description: Đã cấu hình nhận diện khuôn mặt thành công\n"),
    ("                description: Enable face detection\n", "                description: Bật nhận diện khuôn mặt\n"),
    ("        description: Analytics entities retrieved successfully\n", "        description: Đã lấy thực thể analytics thành công\n"),
    ("        description: Statistics retrieved successfully\n", "        description: Đã lấy thống kê thành công\n"),
    ("        description: Instance deleted successfully\n", "        description: Đã xóa instance thành công\n"),
]

def main():
    base = Path("api-specs/openapi/vi/paths")
    if not base.exists():
        print("Not found:", base.resolve())
        return
    count_files = 0
    for yaml_file in base.rglob("*.yaml"):
        try:
            raw = yaml_file.read_text(encoding="utf-8")
            new_raw = raw
            for old, new in REPLACEMENTS:
                new_raw = new_raw.replace(old, new)
            if new_raw != raw:
                yaml_file.write_text(new_raw, encoding="utf-8")
                count_files += 1
        except Exception as e:
            print("Error", yaml_file, e)
    print(f"Updated {count_files} files with common VI replacements.")

if __name__ == "__main__":
    main()
